# This file is licensed under the terms of the MIT license https://opensource.org/license/mit
# Copyright (c) 2021-2025 Marat Reymers

## Golden config for golangci-lint v2.0.2
#
# This is the best config for golangci-lint based on my experience and opinion.
# It is very strict, but not extremely strict.
# Feel free to adapt it to suit your needs.
# If this config helps you, please consider keeping a link to this file (see the next comment).

# Based on https://gist.github.com/maratori/47a4d00457a92aa426dbd48a18776322

version: "2"

issues:
    # Maximum count of issues with the same text.
    # Set to 0 to disable.
    # Default: 3
    max-same-issues: 50

linters:
    enable:
        - asasalint # checks for pass []any as any in variadic func(...any)
        - asciicheck # checks that your code does not contain non-ASCII identifiers
        - bidichk # checks for dangerous unicode character sequences
        - bodyclose # checks whether HTTP response body is closed successfully
        - canonicalheader # checks whether net/http.Header uses canonical header
        - copyloopvar # detects places where loop variables are copied (Go 1.22+)
        - cyclop # checks function and package cyclomatic complexity
        - depguard # checks if package imports are in a list of acceptable packages
        - dupl # tool for code clone detection
        - durationcheck # checks for two durations multiplied together
        - errcheck # checking for unchecked errors, these unchecked errors can be critical bugs in some cases
        - errname # checks that sentinel errors are prefixed with the Err and error types are suffixed with the Error
        - exhaustive # checks exhaustiveness of enum switch statements
        - fatcontext # detects nested contexts in loops
        - funlen # tool for detection of long functions
        - gocheckcompilerdirectives # validates go compiler directive comments (//go:)
        - gochecksumtype # checks exhaustiveness on Go "sum types"
        - gocognit # computes and checks the cognitive complexity of functions
        - goconst # finds repeated strings that could be replaced by a constant
        - gocritic # provides diagnostics that check for bugs, performance and style issues
        - gocyclo # computes and checks the cyclomatic complexity of functions
        - godot # checks if comments end in a period
        - gomoddirectives # manages the use of 'replace', 'retract', and 'excludes' directives in go.mod
        - goprintffuncname # checks that printf-like functions are named with f at the end
        - ineffassign # detects when assignments to existing variables are not used
        - intrange # finds places where for loops could make use of an integer range
        - loggercheck # checks key value pairs for common logger libraries (kitlog,klog,logr,zap)
        - makezero # finds slice declarations with non-zero initial length
        - mirror # reports wrong mirror patterns of bytes/strings usage
        - musttag # enforces field tags in (un)marshaled structs
        - nilerr # finds the code that returns nil even if it checks that the error is not nil
        - nilnil # checks that there is no simultaneous return of nil error and an invalid value
        - noctx # finds sending http request without context.Context
        - nonamedreturns # reports all named returns
        - nosprintfhostport # checks for misuse of Sprintf to construct a host with port in a URL
        - perfsprint # checks that fmt.Sprintf can be replaced with a faster alternative
        - predeclared # finds code that shadows one of Go's predeclared identifiers
        - promlinter # checks Prometheus metrics naming via promlint
        - protogetter # reports direct reads from proto message fields when getters should be used
        - reassign # checks that package variables are not reassigned
        - revive # fast, configurable, extensible, flexible, and beautiful linter for Go, drop-in replacement of golint
        - rowserrcheck # checks whether Err of rows is checked successfully
        - sloglint # ensure consistent code style when using log/slog
        - spancheck # checks for mistakes with OpenTelemetry/Census spans
        - sqlclosecheck # checks that sql.Rows and sql.Stmt are closed
        - staticcheck # is a go vet on steroids, applying a ton of static analysis checks
        - testableexamples # checks if examples are testable (have an expected output)
        - testifylint # checks usage of github.com/stretchr/testify
        - testpackage # makes you use a separate _test package
        - tparallel # detects inappropriate usage of t.Parallel() method in your Go test codes
        - unconvert # removes unnecessary type conversions
        - unparam # reports unused function parameters
        - usestdlibvars # detects the possibility to use variables/constants from the Go standard library
        - wastedassign # finds wasted assignment statements
        - whitespace # detects leading and trailing whitespace
        - gomodguard # [use more powerful depguard] allow and block lists linter for direct Go module dependencies

    # All settings can be found here https://github.com/golangci/golangci-lint/blob/HEAD/.golangci.reference.yml
    settings:
        cyclop:
            # The maximal code complexity to report.
            # Default: 10
            max-complexity: 30
            # The maximal average package complexity.
            # If it's higher than 0.0 (float) the check is enabled
            # Default: 0.0
            package-average: 12.0

        depguard:
            rules:
                prevent_unmaintained_packages:
                    list-mode: lax # allow unless explicitely denied
                    files:
                        - $all
                        - "!$test"
                    allow:
                        - $gostd
                        - github.com/euphoria-laxis/argon2/*
                    deny:
                        - pkg: io/ioutil
                          desc: "replaced by io and os packages since Go 1.16: https://tip.golang.org/doc/go1.16#ioutil"


        errcheck:
            # Report about not checking of errors in type assertions: `a := b.(MyStruct)`.
            # Such cases aren't reported by default.
            # Default: false
            check-type-assertions: true

        exhaustive:
            # Program elements to check for exhaustiveness.
            # Default: [ switch ]
            check:
                - switch
                - map

        funlen:
            # Checks the number of lines in a function.
            # If lower than 0, disable the check.
            # Default: 60
            lines: 60
            # Checks the number of statements in a function.
            # If lower than 0, disable the check.
            # Default: 40
            statements: 30

        gochecksumtype:
            # Presence of `default` case in switch statements satisfies exhaustiveness, if all members are not listed.
            # Default: true
            default-signifies-exhaustive: false

        gocognit:
            # Minimal code complexity to report.
            # Default: 30 (but we recommend 10-20)
            min-complexity: 20

        gocritic:
            # Settings passed to gocritic.
            # The settings key is the name of a supported gocritic checker.
            # The list of supported checkers can be find in https://go-critic.github.io/overview.
            settings:
                captLocal:
                    # Whether to restrict checker to params only.
                    # Default: true
                    paramsOnly: false
                underef:
                    # Whether to skip (*x).method() calls where x is a pointer receiver.
                    # Default: true
                    skipRecvDeref: false

        govet:
            # Enable all analyzers.
            # Default: false
            enable-all: false
            # Disable analyzers by name.
            # Run `go tool vet help` to see all analyzers.
            # Default: []
            disable:
                - fieldalignment # too strict
                - assign # use predeclared + reassign instead
            # Settings per analyzer.
            settings:

        inamedparam:
            # Skips check for interface methods with only a single parameter.
            # Default: false
            skip-single-param: true

        mnd:
            # List of function patterns to exclude from analysis.
            # Values always ignored: `time.Date`,
            # `strconv.FormatInt`, `strconv.FormatUint`, `strconv.FormatFloat`,
            # `strconv.ParseInt`, `strconv.ParseUint`, `strconv.ParseFloat`.
            # Default: []
            ignored-functions:
                - args.Error
                - flag.Arg
                - flag.Duration.*
                - flag.Float.*
                - flag.Int.*
                - flag.Uint.*
                - os.Chmod
                - os.Mkdir.*
                - os.OpenFile
                - os.WriteFile
                - prometheus.ExponentialBuckets.*
                - prometheus.LinearBuckets

        nakedret:
            # Make an issue if func has more lines of code than this setting, and it has naked returns.
            # Default: 30
            max-func-lines: 30

        nolintlint:
            # Exclude following linters from requiring an explanation.
            # Default: []
            allow-no-explanation: [ funlen, gocognit, all ]
            # Enable to require an explanation of nonzero length after each nolint directive.
            # Default: false
            require-explanation: true
            # Enable to require nolint directives to mention the specific linter being suppressed.
            # Default: false
            require-specific: true

        perfsprint:
            # Optimizes into strings concatenation.
            # Default: true
            strconcat: false

        reassign:
            # Patterns for global variable names that are checked for reassignment.
            # See https://github.com/curioswitch/go-reassign#usage
            # Default: ["EOF", "Err.*"]
            patterns:
                - ".*"
        revive:
            exclude: '_test.go'

        rowserrcheck:
            # database/sql is always checked
            # Default: []
            packages:
                - github.com/jmoiron/sqlx

        sloglint:
            # Enforce not using global loggers.
            # Values:
            # - "": disabled
            # - "all": report all global loggers
            # - "default": report only the default slog logger
            # https://github.com/go-simpler/sloglint?tab=readme-ov-file#no-global
            # Default: ""
            no-global: all
            # Enforce using methods that accept a context.
            # Values:
            # - "": disabled
            # - "all": report all contextless calls
            # - "scope": report only if a context exists in the scope of the outermost function
            # https://github.com/go-simpler/sloglint?tab=readme-ov-file#context-only
            # Default: ""
            context: scope

        staticcheck:
            # SAxxxx checks in https://staticcheck.dev/docs/configuration/options/#checks
            # Example (to disable some checks): [ "all", "-SA1000", "-SA1001"]
            # Default: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]
            checks:
                - all
                # Incorrect or missing package comment.
                # https://staticcheck.dev/docs/checks/#ST1000
                - -ST1000
                # Use consistent method receiver names.
                # https://staticcheck.dev/docs/checks/#ST1016
                - -ST1016
                # Omit embedded fields from selector expression.
                # https://staticcheck.dev/docs/checks/#QF1008
                - -QF1008

        usetesting:
            # Enable/disable `os.TempDir()` detections.
            # Default: false
            os-temp-dir: true

    exclusions:
        # Predefined exclusion rules.
        # Default: []
        presets:
            - std-error-handling
            - common-false-positives
        # Excluding configuration per-path, per-linter, per-text and per-source.
        rules:
            - linters:
                  - lll
              source: "^//go:generate "
            - text: 'should have a package comment'
              linters: [ revive ]
            # Exclude some `staticcheck` messages.
            -   linters:
                    - staticcheck
                text: "SA9003:"
            - text: 'exported \S+ \S+ should have comment( \(or a comment on this block\))? or be unexported'
              linters: [ revive ]
              path: 'hashing/.go'
            - text: 'package comment should be of the form ".+"'
              source: '// ?(nolint|TODO)'
              linters: [ revive ]
              path: 'hashing/.go'
            - text: 'comment on exported \S+ \S+ should be of the form ".+"'
              path: 'hashing/.go'
              source: '// ?(nolint|TODO)'
              linters: [ revive, staticcheck ]
            - path: 'hashing/.go'
              exclude: '_test.go'
              linters:
                  - bodyclose
                  - dupl
                  - errcheck
                  - funlen
                  - goconst
                  - noctx
                  - wrapcheck
